include:
  - Scripts/Modules.yml
options:
  createIntermediateGroups: true
    
attributes:
  LastSwiftUpdateCheck: 1210
  LastUpgradeCheck: 1100
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configurations/debug.xcconfig
  Release: Configurations/release.xcconfig
name: VCamera
schemes:
  VCamera:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        VCamera:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
targets:
  VCamera:
    dependencies:
    - target : Authority
      embed: false
    - target: Galilei
      embed: false
    - target: Vincent
      embed: false
    - target: MediaBox
      embed: false
    - sdk : AVFoundation.framework
    - sdk : Photos.framework
    platform: iOS
    sources:
      - path: "VCamera"
    type: application
